rootProject.name = "text-rpg"

include(":application:main")
include(":application:shared")
include(":application:monitoring")
include(":application:security")
include(":application:documentation")
include(":application:mediator")
include(":application:acl")
include(":application:mail")
include(":application:event-store")
include(":application:redis")
include(":application:test-utils")
include(":application:account")
include(":application:world")
