version: "3.8"

x-clickhouse-defaults: &clickhouse-defaults
  restart: on-failure
  image: clickhouse/clickhouse-server:23.7.3-alpine
  tty: true
  depends_on:
    - zookeeper-1
  logging:
    options:
      max-size: 50m
      max-file: "3"
  healthcheck:
    test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

x-clickhouse-depend: &clickhouse-depend
  depends_on:
    clickhouse:
      condition: service_healthy


services:
  zookeeper-1:
    image: bitnami/zookeeper:3.7.1
    container_name: zookeeper-1
    hostname: zookeeper-1
    user: root
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - ./data/zookeeper-1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
    networks:
      text-rpg-net:
        aliases:
          - zookeeper-1

  clickhouse:
    <<: *clickhouse-defaults
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9181:9181"
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.xml
      - ./custom-function.xml:/etc/clickhouse-server/custom-function.xml
      - ./clickhouse-cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./data/clickhouse/:/var/lib/clickhouse/
      - ./user_scripts:/var/lib/clickhouse/user_scripts/
    networks:
      text-rpg-net:
        aliases:
          - clickhouse

  alertmanager:
    image: signoz/alertmanager:${ALERTMANAGER_TAG:-0.23.2}
    volumes:
      - ./data/alertmanager:/data
    depends_on:
      query-service:
        condition: service_healthy
    restart: on-failure
    command:
      - --queryService.url=http://query-service:8085
      - --storage.path=/data
    networks:
      text-rpg-net:
        aliases:
          - alertmanager

  query-service:
    image: signoz/query-service:${DOCKER_TAG:-0.27.0}
    container_name: query-service
    command: [ "-config=/root/config/prometheus.yml" ]
    volumes:
      - ./prometheus.yml:/root/config/prometheus.yml
      - ./dashboards:/root/config/dashboards
      - ./data/signoz/:/var/lib/signoz/
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000/?database=signoz_traces
      - ALERTMANAGER_API_PREFIX=http://alertmanager:9093/api/
      - SIGNOZ_LOCAL_DB_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
    restart: on-failure
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "localhost:8080/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      text-rpg-net:
        aliases:
          - query-service
    <<: *clickhouse-depend

  frontend:
    image: signoz/frontend:${DOCKER_TAG:-0.27.0}
    container_name: frontend
    restart: on-failure
    depends_on:
      - alertmanager
      - query-service
    ports:
      - "3301:3301"
    volumes:
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf
    networks:
      text-rpg-net:
        aliases:
          - frontend

  otel-collector:
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-0.79.6}
    command: [ "--config=/etc/otel-collector-config.yaml", "--feature-gates=-pkg.translator.prometheus.NormalizeName" ]
    user: root # required for reading docker container logs
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - DOCKER_MULTI_NODE_CLUSTER=false
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    restart: on-failure
    networks:
      text-rpg-net:
        aliases:
          - otel-collector
    <<: *clickhouse-depend

  otel-collector-metrics:
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-0.79.6}
    command: [ "--config=/etc/otel-collector-metrics-config.yaml", "--feature-gates=-pkg.translator.prometheus.NormalizeName" ]
    volumes:
      - ./otel-collector-metrics-config.yaml:/etc/otel-collector-metrics-config.yaml
    restart: on-failure
    networks:
      text-rpg-net:
        aliases:
          - otel-collector-metrics
    <<: *clickhouse-depend

  text-rpg-eventstore-db:
    image: eventstore/eventstore:23.6.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-db-text-rpg-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-db-text-rpg-volume-logs
        target: /var/log/eventstore
    networks:
      text-rpg-net:
        aliases:
          - text-rpg-eventstore-db

  text-rpg:
    image: text-rpg-ktor:0.0.1
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_RESOURCE_ATTRIBUTES=service.name=text-rpg,service.version=0.0.1
      - OTEL_METRICS_URL=http://otel-collector:4318/v1/metrics
      - MONITORING_ENABLED=true
      - DEPLOY_ENV=dev
      - VCS_VERSION=0.0.1
    depends_on:
      otel-collector:
        condition: service_started
    networks:
      text-rpg-net:
        aliases:
          - text-rpg

volumes:
  eventstore-db-text-rpg-volume-data:
  eventstore-db-text-rpg-volume-logs:
  mongodb_master_data:
    driver: local

networks:
  text-rpg-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16

# vm options: -javaagent:./.docker/open-telemetry/opentelemetry-javaagent.jar
# env:OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317;OTEL_LOGS_EXPORTER=otlp;OTEL_METRICS_EXPORTER=otlp;OTEL_RESOURCE_ATTRIBUTES=service.name=text-rpg